// frontend-react/src/components/budgets/Budgets.tsx
import React, { useState, useEffect } from 'react';
import {
  Box,
  Card,
  CardContent,
  CardHeader,
  CardActions,
  Typography,
  Button,
  CircularProgress,
  Grid,
  Avatar,
  LinearProgress,
  Snackbar,
  Alert,
} from '@mui/material';
import {
  Add as AddIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  AccountBalanceWallet as WalletIcon,
  CheckCircle as CheckCircleIcon,
  Warning as WarningIcon,
  Error as ErrorIcon,
} from '@mui/icons-material';
import { Budget, Category } from '../../types';
import { budgetService, categoryService } from '../../services';
import BudgetDialog from './BudgetDialog';

const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
  }).format(amount);
};

const Budgets: React.FC = () => {
  const [budgets, setBudgets] = useState<Budget[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [selectedBudget, setSelectedBudget] = useState<Budget | undefined>();
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  useEffect(() => {
    loadCategories();
    loadBudgets();
  }, []);

  const loadCategories = async () => {
    try {
      const data = await categoryService.getCategories();
      setCategories(data);
    } catch (err) {
      setError('Failed to load categories');
    }
  };

  const loadBudgets = async () => {
    setLoading(true);
    try {
      const data = await budgetService.getBudgets();
      setBudgets(data);
    } catch (err) {
      setError('Failed to load budgets');
    } finally {
      setLoading(false);
    }
  };

  const handleOpenDialog = (budget?: Budget) => {
    setSelectedBudget(budget);
    setDialogOpen(true);
  };

  const handleCloseDialog = () => {
    setDialogOpen(false);
    setSelectedBudget(undefined);
  };

  const handleDeleteBudget = async (budget: Budget) => {
    if (!window.confirm('Are you sure you want to delete this budget?')) {
      return;
    }

    try {
      await budgetService.deleteBudget(budget.id!);
      setSuccess('Budget deleted successfully');
      loadBudgets();
    } catch (err) {
      setError('Failed to delete budget');
    }
  };

  const getStatusClass = (budget: Budget): 'success' | 'warning' | 'error' => {
    if (!budget.percentage) return 'success';
    if (budget.percentage >= 100) return 'error';
    if (budget.percentage >= 80) return 'warning';
    return 'success';
  };

  const getStatusIcon = (budget: Budget) => {
    const status = getStatusClass(budget);
    if (status === 'error') return <ErrorIcon color="error" />;
    if (status === 'warning') return <WarningIcon color="warning" />;
    return <CheckCircleIcon color="success" />;
  };

  return (
    <Box sx={{ maxWidth: 1200, mx: 'auto' }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h4" component="h1">
          Budgets
        </Typography>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={() => handleOpenDialog()}
        >
          Add Budget
        </Button>
      </Box>

      {loading ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', p: 6 }}>
          <CircularProgress />
        </Box>
      ) : budgets.length === 0 ? (
        <Card>
          <CardContent sx={{ textAlign: 'center', py: 8 }}>
            <WalletIcon sx={{ fontSize: 64, color: 'action.disabled', mb: 2 }} />
            <Typography variant="h6" gutterBottom>
              No budgets set
            </Typography>
            <Typography color="text.secondary">
              Create your first budget to start tracking your spending!
            </Typography>
          </CardContent>
        </Card>
      ) : (
        <Grid container spacing={3}>
          {budgets.map((budget) => (
            <Grid item xs={12} sm={6} md={4} key={budget.id}>
              <Card
                sx={{
                  height: '100%',
                  transition: 'transform 0.2s',
                  '&:hover': { transform: 'translateY(-4px)', boxShadow: 3 },
                }}
              >
                <CardHeader
                  avatar={
                    <Avatar
                      sx={{ bgcolor: budget.category?.color || 'primary.main' }}
                    >
                      <WalletIcon />
                    </Avatar>
                  }
                  title={budget.category?.name}
                  subheader="Monthly Budget"
                />
                <CardContent>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 2 }}>
                    <Box sx={{ textAlign: 'center' }}>
                      <Typography variant="caption" color="text.secondary">
                        Budget
                      </Typography>
                      <Typography variant="body1" fontWeight={500}>
                        {formatCurrency(budget.amount)}
                      </Typography>
                    </Box>
                    <Box sx={{ textAlign: 'center' }}>
                      <Typography variant="caption" color="text.secondary">
                        Spent
                      </Typography>
                      <Typography
                        variant="body1"
                        fontWeight={500}
                        color={`${getStatusClass(budget)}.main`}
                      >
                        {formatCurrency(budget.spent || 0)}
                      </Typography>
                    </Box>
                    <Box sx={{ textAlign: 'center' }}>
                      <Typography variant="caption" color="text.secondary">
                        Remaining
                      </Typography>
                      <Typography variant="body1" fontWeight={500}>
                        {formatCurrency(budget.remaining || 0)}
                      </Typography>
                    </Box>
                  </Box>

                  <Box sx={{ mt: 2 }}>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                      <Typography variant="body2">
                        {Math.round(budget.percentage || 0)}% Used
                      </Typography>
                      {getStatusIcon(budget)}
                    </Box>
                    <LinearProgress
                      variant="determinate"
                      value={Math.min(budget.percentage || 0, 100)}
                      color={getStatusClass(budget)}
                      sx={{ height: 8, borderRadius: 4 }}
                    />
                  </Box>
                </CardContent>
                <CardActions>
                  <Button
                    size="small"
                    startIcon={<EditIcon />}
                    onClick={() => handleOpenDialog(budget)}
                  >
                    Edit
                  </Button>
                  <Button
                    size="small"
                    color="error"
                    startIcon={<DeleteIcon />}
                    onClick={() => handleDeleteBudget(budget)}
                  >
                    Delete
                  </Button>
                </CardActions>
              </Card>
            </Grid>
          ))}
        </Grid>
      )}

      <BudgetDialog
        open={dialogOpen}
        onClose={handleCloseDialog}
        onSaved={() => {
          setSuccess(`Budget ${selectedBudget ? 'updated' : 'created'} successfully`);
          loadBudgets();
        }}
        budget={selectedBudget}
        categories={categories}
      />

      <Snackbar
        open={!!error}
        autoHideDuration={3000}
        onClose={() => setError(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert severity="error" onClose={() => setError(null)}>
          {error}
        </Alert>
      </Snackbar>

      <Snackbar
        open={!!success}
        autoHideDuration={3000}
        onClose={() => setSuccess(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert severity="success" onClose={() => setSuccess(null)}>
          {success}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default Budgets;

// frontend/src/app/features/budgets/budgets.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { BudgetService } from '../../core/services/budget.service';
import { CategoryService } from '../../core/services/category.service';
import { Budget } from '../../core/models/budget.model';
import { Category } from '../../core/models/category.model';
import { BudgetDialogComponent } from './budget-dialog/budget-dialog.component';

@Component({
  selector: 'app-budgets',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatProgressBarModule,
    MatDialogModule,
    MatSnackBarModule,
    MatProgressSpinnerModule
  ],
  template: `
    <div class="budgets-container">
      <div class="header">
        <h1>Budgets</h1>
        <button mat-raised-button color="primary" (click)="openBudgetDialog()">
          <mat-icon>add</mat-icon>
          Add Budget
        </button>
      </div>

      <mat-card *ngIf="loading" class="loading-card">
        <mat-spinner></mat-spinner>
      </mat-card>

      <div class="budgets-grid" *ngIf="!loading">
        <mat-card *ngFor="let budget of budgets" class="budget-card">
          <mat-card-header>
            <div mat-card-avatar class="category-icon" 
                 [style.background-color]="budget.category?.color">
              <mat-icon>{{ budget.category?.icon || 'account_balance_wallet' }}</mat-icon>
            </div>
            <mat-card-title>{{ budget.category?.name }}</mat-card-title>
            <mat-card-subtitle>Monthly Budget</mat-card-subtitle>
          </mat-card-header>

          <mat-card-content>
            <div class="budget-amounts">
              <div class="amount-item">
                <span class="label">Budget</span>
                <span class="value">\${{ budget.amount | number:'1.2-2' }}</span>
              </div>
              <div class="amount-item">
                <span class="label">Spent</span>
                <span class="value" [class]="getStatusClass(budget)">\${{ budget.spent | number:'1.2-2' }}</span>
              </div>
              <div class="amount-item">
                <span class="label">Remaining</span>
                <span class="value">\${{ budget.remaining | number:'1.2-2' }}</span>
              </div>
            </div>

            <div class="progress-section">
              <div class="progress-header">
                <span>{{ budget.percentage | number:'1.0-0' }}% Used</span>
                <mat-icon [class]="getStatusClass(budget)">
                  {{ getStatusIcon(budget) }}
                </mat-icon>
              </div>
              <mat-progress-bar 
                mode="determinate" 
                [value]="budget.percentage"
                [class]="getStatusClass(budget)">
              </mat-progress-bar>
            </div>
          </mat-card-content>

          <mat-card-actions>
            <button mat-button (click)="openBudgetDialog(budget)">
              <mat-icon>edit</mat-icon>
              Edit
            </button>
            <button mat-button color="warn" (click)="deleteBudget(budget)">
              <mat-icon>delete</mat-icon>
              Delete
            </button>
          </mat-card-actions>
        </mat-card>

        <div *ngIf="budgets.length === 0" class="empty-state">
          <mat-icon>account_balance_wallet</mat-icon>
          <h3>No budgets set</h3>
          <p>Create your first budget to start tracking your spending!</p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .budgets-container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }

    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 20px;
    }

    .header h1 {
      margin: 0;
    }

    .loading-card {
      display: flex;
      justify-content: center;
      padding: 40px;
    }

    .budgets-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
      gap: 20px;
    }

    .budget-card {
      transition: transform 0.2s;
    }

    .budget-card:hover {
      transform: translateY(-4px);
      box-shadow: 0 4px 8px rgba(0,0,0,0.2);
    }

    .category-icon {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 40px;
      height: 40px;
      border-radius: 50%;
      color: white;
    }

    .budget-amounts {
      display: flex;
      justify-content: space-between;
      margin: 20px 0;
    }

    .amount-item {
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    .amount-item .label {
      font-size: 12px;
      color: rgba(0, 0, 0, 0.6);
      margin-bottom: 5px;
    }

    .amount-item .value {
      font-size: 18px;
      font-weight: 500;
    }

    .progress-section {
      margin-top: 15px;
    }

    .progress-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 8px;
    }

    .good {
      color: #4CAF50;
    }

    .warning {
      color: #FF9800;
    }

    .exceeded {
      color: #F44336;
    }

    mat-progress-bar.good::ng-deep .mat-progress-bar-fill::after {
      background-color: #4CAF50;
    }

    mat-progress-bar.warning::ng-deep .mat-progress-bar-fill::after {
      background-color: #FF9800;
    }

    mat-progress-bar.exceeded::ng-deep .mat-progress-bar-fill::after {
      background-color: #F44336;
    }

    @media (max-width: 768px) {
      .budgets-grid {
        grid-template-columns: 1fr;
      }
    }
  `]
})
export class BudgetsComponent implements OnInit {
  budgets: Budget[] = [];
  categories: Category[] = [];
  loading = false;

  constructor(
    private budgetService: BudgetService,
    private categoryService: CategoryService,
    private dialog: MatDialog,
    private snackBar: MatSnackBar
  ) {}

  ngOnInit() {
    this.loadCategories();
    this.loadBudgets();
  }

  loadCategories() {
    this.categoryService.getCategories().subscribe({
      next: (categories) => {
        this.categories = categories;
      }
    });
  }

  loadBudgets() {
    this.loading = true;
    this.budgetService.getBudgets().subscribe({
      next: (budgets) => {
        this.budgets = budgets;
        this.loading = false;
      },
      error: (error) => {
        this.loading = false;
        this.snackBar.open('Failed to load budgets', 'Close', { duration: 3000 });
      }
    });
  }

  openBudgetDialog(budget?: Budget) {
    const dialogRef = this.dialog.open(BudgetDialogComponent, {
      width: '500px',
      data: { budget, categories: this.categories }
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.loadBudgets();
      }
    });
  }

  deleteBudget(budget: Budget) {
    if (confirm('Are you sure you want to delete this budget?')) {
      this.budgetService.deleteBudget(budget.id!).subscribe({
        next: () => {
          this.snackBar.open('Budget deleted successfully', 'Close', { duration: 3000 });
          this.loadBudgets();
        },
        error: (error) => {
          this.snackBar.open('Failed to delete budget', 'Close', { duration: 3000 });
        }
      });
    }
  }

  getStatusClass(budget: Budget): string {
    if (!budget.percentage) return 'good';
    if (budget.percentage >= 100) return 'exceeded';
    if (budget.percentage >= 80) return 'warning';
    return 'good';
  }

  getStatusIcon(budget: Budget): string {
    const status = this.getStatusClass(budget);
    if (status === 'exceeded') return 'error';
    if (status === 'warning') return 'warning';
    return 'check_circle';
  }
}
