// frontend/src/app/features/recurring-bills/recurring-bills.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { RecurringBillService } from '../../core/services/recurring-bill.service';
import { CategoryService } from '../../core/services/category.service';
import { RecurringBill } from '../../core/models/recurring-bill.model';
import { Category } from '../../core/models/category.model';
import { RecurringBillDialogComponent } from './recurring-bill-dialog/recurring-bill-dialog.component';

@Component({
  selector: 'app-recurring-bills',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatChipsModule,
    MatDialogModule,
    MatSnackBarModule,
    MatProgressSpinnerModule
  ],
  template: `
    <div class="bills-container">
      <div class="header">
        <h1>Recurring Bills</h1>
        <button mat-raised-button color="primary" (click)="openBillDialog()">
          <mat-icon>add</mat-icon>
          Add Bill
        </button>
      </div>

      <mat-card *ngIf="loading" class="loading-card">
        <mat-spinner></mat-spinner>
      </mat-card>

      <div class="bills-list" *ngIf="!loading">
        <mat-card *ngFor="let bill of bills" class="bill-card" 
                  [class.overdue]="bill.isOverdue"
                  [class.upcoming]="bill.needsReminder">
          <mat-card-header>
            <div mat-card-avatar class="category-icon" 
                 [style.background-color]="bill.category?.color">
              <mat-icon>{{ bill.category?.icon || 'event_repeat' }}</mat-icon>
            </div>
            <mat-card-title>{{ bill.name }}</mat-card-title>
            <mat-card-subtitle>
              {{ bill.category?.name }} • {{ bill.frequency }}
            </mat-card-subtitle>
          </mat-card-header>

          <mat-card-content>
            <div class="bill-amount">\${{ bill.amount | number:'1.2-2' }}</div>
            
            <div class="bill-info">
              <div class="info-item">
                <mat-icon>event</mat-icon>
                <span>Due: {{ bill.nextDueDate | date }}</span>
              </div>
              <div class="info-item" *ngIf="bill.daysUntilDue !== undefined">
                <mat-icon>schedule</mat-icon>
                <span>
                  {{ bill.isOverdue ? 'Overdue by ' + Math.abs(bill.daysUntilDue) : 
                     'In ' + bill.daysUntilDue }} days
                </span>
              </div>
            </div>

            <mat-chip-set>
              <mat-chip *ngIf="bill.isOverdue" class="overdue-chip">
                <mat-icon>error</mat-icon>
                Overdue
              </mat-chip>
              <mat-chip *ngIf="bill.needsReminder && !bill.isOverdue" class="reminder-chip">
                <mat-icon>notifications</mat-icon>
                Due Soon
              </mat-chip>
              <mat-chip *ngIf="!bill.isActive" class="inactive-chip">
                Inactive
              </mat-chip>
            </mat-chip-set>

            <p *ngIf="bill.notes" class="bill-notes">{{ bill.notes }}</p>
          </mat-card-content>

          <mat-card-actions>
            <button mat-button color="primary" (click)="markAsPaid(bill)">
              <mat-icon>check_circle</mat-icon>
              Mark Paid
            </button>
            <button mat-button (click)="openBillDialog(bill)">
              <mat-icon>edit</mat-icon>
              Edit
            </button>
            <button mat-button color="warn" (click)="deleteBill(bill)">
              <mat-icon>delete</mat-icon>
              Delete
            </button>
          </mat-card-actions>
        </mat-card>

        <div *ngIf="bills.length === 0" class="empty-state">
          <mat-icon>event_repeat</mat-icon>
          <h3>No recurring bills</h3>
          <p>Add your recurring bills to track and get reminders!</p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .bills-container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }

    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 20px;
    }

    .header h1 {
      margin: 0;
    }

    .loading-card {
      display: flex;
      justify-content: center;
      padding: 40px;
    }

    .bills-list {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
      gap: 20px;
    }

    .bill-card {
      transition: transform 0.2s;
    }

    .bill-card:hover {
      transform: translateY(-4px);
      box-shadow: 0 4px 8px rgba(0,0,0,0.2);
    }

    .bill-card.overdue {
      border-left: 4px solid #F44336;
    }

    .bill-card.upcoming {
      border-left: 4px solid #FF9800;
    }

    .category-icon {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 40px;
      height: 40px;
      border-radius: 50%;
      color: white;
    }

    .bill-amount {
      font-size: 24px;
      font-weight: 500;
      color: #3f51b5;
      margin: 10px 0;
    }

    .bill-info {
      margin: 15px 0;
    }

    .info-item {
      display: flex;
      align-items: center;
      gap: 8px;
      margin: 8px 0;
      color: rgba(0, 0, 0, 0.7);
    }

    .info-item mat-icon {
      font-size: 20px;
      width: 20px;
      height: 20px;
    }

    mat-chip-set {
      margin: 10px 0;
    }

    .overdue-chip {
      background-color: #F44336;
      color: white;
    }

    .reminder-chip {
      background-color: #FF9800;
      color: white;
    }

    .inactive-chip {
      background-color: #9E9E9E;
      color: white;
    }

    .bill-notes {
      color: rgba(0, 0, 0, 0.6);
      margin: 10px 0;
      font-size: 14px;
    }

    @media (max-width: 768px) {
      .bills-list {
        grid-template-columns: 1fr;
      }
    }
  `]
})
export class RecurringBillsComponent implements OnInit {
  bills: RecurringBill[] = [];
  categories: Category[] = [];
  loading = false;
  Math = Math;

  constructor(
    private billService: RecurringBillService,
    private categoryService: CategoryService,
    private dialog: MatDialog,
    private snackBar: MatSnackBar
  ) {}

  ngOnInit() {
    this.loadCategories();
    this.loadBills();
  }

  loadCategories() {
    this.categoryService.getCategories().subscribe({
      next: (categories) => {
        this.categories = categories;
      }
    });
  }

  loadBills() {
    this.loading = true;
    this.billService.getBills().subscribe({
      next: (bills) => {
        this.bills = bills.sort((a, b) => {
          if (a.isOverdue && !b.isOverdue) return -1;
          if (!a.isOverdue && b.isOverdue) return 1;
          return new Date(a.nextDueDate).getTime() - new Date(b.nextDueDate).getTime();
        });
        this.loading = false;
      },
      error: (error) => {
        this.loading = false;
        this.snackBar.open('Failed to load bills', 'Close', { duration: 3000 });
      }
    });
  }

  openBillDialog(bill?: RecurringBill) {
    const dialogRef = this.dialog.open(RecurringBillDialogComponent, {
      width: '500px',
      data: { bill, categories: this.categories }
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.loadBills();
      }
    });
  }

  markAsPaid(bill: RecurringBill) {
    this.billService.markAsPaid(bill.id!).subscribe({
      next: () => {
        this.snackBar.open('Bill marked as paid', 'Close', { duration: 3000 });
        this.loadBills();
      },
      error: (error) => {
        this.snackBar.open('Failed to mark bill as paid', 'Close', { duration: 3000 });
      }
    });
  }

  deleteBill(bill: RecurringBill) {
    if (confirm('Are you sure you want to delete this bill?')) {
      this.billService.deleteBill(bill.id!).subscribe({
        next: () => {
          this.snackBar.open('Bill deleted successfully', 'Close', { duration: 3000 });
          this.loadBills();
        },
        error: (error) => {
          this.snackBar.open('Failed to delete bill', 'Close', { duration: 3000 });
        }
      });
    }
  }
}

// frontend-react/src/components/recurring-bills/RecurringBills.tsx
import React, { useState, useEffect } from 'react';
import {
  Box,
  Card,
  CardContent,
  CardHeader,
  CardActions,
  Typography,
  Button,
  CircularProgress,
  Grid,
  Avatar,
  Chip,
  Snackbar,
  Alert,
} from '@mui/material';
import {
  Add as AddIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  EventRepeat as EventRepeatIcon,
  Event as EventIcon,
  Schedule as ScheduleIcon,
  CheckCircle as CheckCircleIcon,
  Error as ErrorIcon,
  Notifications as NotificationsIcon,
} from '@mui/icons-material';
import { RecurringBill, Category } from '../../types';
import { recurringBillService, categoryService } from '../../services';
import RecurringBillDialog from './RecurringBillDialog';

const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
  }).format(amount);
};

const formatDate = (dateString: string): string => {
  return new Date(dateString).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
};

const RecurringBills: React.FC = () => {
  const [bills, setBills] = useState<RecurringBill[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [selectedBill, setSelectedBill] = useState<RecurringBill | undefined>();
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  useEffect(() => {
    loadCategories();
    loadBills();
  }, []);

  const loadCategories = async () => {
    try {
      const data = await categoryService.getCategories();
      setCategories(data);
    } catch (err) {
      setError('Failed to load categories');
    }
  };

  const loadBills = async () => {
    setLoading(true);
    try {
      const data = await recurringBillService.getBills();
      // Sort: overdue first, then by due date
      const sorted = data.sort((a, b) => {
        if (a.isOverdue && !b.isOverdue) return -1;
        if (!a.isOverdue && b.isOverdue) return 1;
        return new Date(a.nextDueDate).getTime() - new Date(b.nextDueDate).getTime();
      });
      setBills(sorted);
    } catch (err) {
      setError('Failed to load bills');
    } finally {
      setLoading(false);
    }
  };

  const handleOpenDialog = (bill?: RecurringBill) => {
    setSelectedBill(bill);
    setDialogOpen(true);
  };

  const handleCloseDialog = () => {
    setDialogOpen(false);
    setSelectedBill(undefined);
  };

  const handleMarkAsPaid = async (bill: RecurringBill) => {
    try {
      await recurringBillService.markAsPaid(bill.id!);
      setSuccess('Bill marked as paid');
      loadBills();
    } catch (err) {
      setError('Failed to mark bill as paid');
    }
  };

  const handleDeleteBill = async (bill: RecurringBill) => {
    if (!window.confirm('Are you sure you want to delete this bill?')) {
      return;
    }

    try {
      await recurringBillService.deleteBill(bill.id!);
      setSuccess('Bill deleted successfully');
      loadBills();
    } catch (err) {
      setError('Failed to delete bill');
    }
  };

  return (
    <Box sx={{ maxWidth: 1200, mx: 'auto' }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h4" component="h1">
          Recurring Bills
        </Typography>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={() => handleOpenDialog()}
        >
          Add Bill
        </Button>
      </Box>

      {loading ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', p: 6 }}>
          <CircularProgress />
        </Box>
      ) : bills.length === 0 ? (
        <Card>
          <CardContent sx={{ textAlign: 'center', py: 8 }}>
            <EventRepeatIcon sx={{ fontSize: 64, color: 'action.disabled', mb: 2 }} />
            <Typography variant="h6" gutterBottom>
              No recurring bills
            </Typography>
            <Typography color="text.secondary">
              Add your recurring bills to track and get reminders!
            </Typography>
          </CardContent>
        </Card>
      ) : (
        <Grid container spacing={3}>
          {bills.map((bill) => (
            <Grid item xs={12} sm={6} md={4} key={bill.id}>
              <Card
                sx={{
                  height: '100%',
                  transition: 'transform 0.2s',
                  '&:hover': { transform: 'translateY(-4px)', boxShadow: 3 },
                  borderLeft: bill.isOverdue
                    ? '4px solid #f44336'
                    : bill.needsReminder
                    ? '4px solid #ff9800'
                    : undefined,
                }}
              >
                <CardHeader
                  avatar={
                    <Avatar
                      sx={{ bgcolor: bill.category?.color || 'primary.main' }}
                    >
                      <EventRepeatIcon />
                    </Avatar>
                  }
                  title={bill.name}
                  subheader={`${bill.category?.name} • ${bill.frequency}`}
                />
                <CardContent>
                  <Typography variant="h5" sx={{ color: 'primary.main', mb: 2 }}>
                    {formatCurrency(bill.amount)}
                  </Typography>

                  <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1, mb: 2 }}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, color: 'text.secondary' }}>
                      <EventIcon fontSize="small" />
                      <Typography variant="body2">
                        Due: {formatDate(bill.nextDueDate)}
                      </Typography>
                    </Box>
                    {bill.daysUntilDue !== undefined && (
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, color: 'text.secondary' }}>
                        <ScheduleIcon fontSize="small" />
                        <Typography variant="body2">
                          {bill.isOverdue
                            ? `Overdue by ${Math.abs(bill.daysUntilDue)} days`
                            : `In ${bill.daysUntilDue} days`}
                        </Typography>
                      </Box>
                    )}
                  </Box>

                  <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                    {bill.isOverdue && (
                      <Chip
                        icon={<ErrorIcon />}
                        label="Overdue"
                        size="small"
                        color="error"
                      />
                    )}
                    {bill.needsReminder && !bill.isOverdue && (
                      <Chip
                        icon={<NotificationsIcon />}
                        label="Due Soon"
                        size="small"
                        color="warning"
                      />
                    )}
                    {!bill.isActive && (
                      <Chip
                        label="Inactive"
                        size="small"
                        color="default"
                      />
                    )}
                  </Box>

                  {bill.notes && (
                    <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
                      {bill.notes}
                    </Typography>
                  )}
                </CardContent>
                <CardActions>
                  <Button
                    size="small"
                    color="primary"
                    startIcon={<CheckCircleIcon />}
                    onClick={() => handleMarkAsPaid(bill)}
                  >
                    Mark Paid
                  </Button>
                  <Button
                    size="small"
                    startIcon={<EditIcon />}
                    onClick={() => handleOpenDialog(bill)}
                  >
                    Edit
                  </Button>
                  <Button
                    size="small"
                    color="error"
                    startIcon={<DeleteIcon />}
                    onClick={() => handleDeleteBill(bill)}
                  >
                    Delete
                  </Button>
                </CardActions>
              </Card>
            </Grid>
          ))}
        </Grid>
      )}

      <RecurringBillDialog
        open={dialogOpen}
        onClose={handleCloseDialog}
        onSaved={() => {
          setSuccess(`Bill ${selectedBill ? 'updated' : 'created'} successfully`);
          loadBills();
        }}
        bill={selectedBill}
        categories={categories}
      />

      <Snackbar
        open={!!error}
        autoHideDuration={3000}
        onClose={() => setError(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert severity="error" onClose={() => setError(null)}>
          {error}
        </Alert>
      </Snackbar>

      <Snackbar
        open={!!success}
        autoHideDuration={3000}
        onClose={() => setSuccess(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert severity="success" onClose={() => setSuccess(null)}>
          {success}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default RecurringBills;
