// frontend-react/src/components/dashboard/Dashboard.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Card,
  CardContent,
  CardHeader,
  Typography,
  CircularProgress,
  Grid,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Button,
  LinearProgress,
} from '@mui/material';
import {
  AccountBalanceWallet as WalletIcon,
  Savings as SavingsIcon,
  EventRepeat as EventRepeatIcon,
  Flag as FlagIcon,
} from '@mui/icons-material';
import { Doughnut, Line } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  ArcElement,
  Tooltip,
  Legend,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Filler,
} from 'chart.js';
import { dashboardService } from '../../services';
import { DashboardStats, SpendingByCategory, SpendingTrend, Budget, Expense } from '../../types';

ChartJS.register(
  ArcElement,
  Tooltip,
  Legend,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Filler
);

const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
  }).format(amount);
};

const formatDate = (dateString: string): string => {
  return new Date(dateString).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
};

const Dashboard: React.FC = () => {
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState<DashboardStats>({
    totalExpenses: 0,
    totalBudget: 0,
    budgetRemaining: 0,
    budgetPercentage: 0,
    upcomingBills: 0,
    activeSavingsGoals: 0,
    totalSaved: 0,
  });
  const [spendingByCategory, setSpendingByCategory] = useState<SpendingByCategory[]>([]);
  const [spendingTrend, setSpendingTrend] = useState<SpendingTrend[]>([]);
  const [budgets, setBudgets] = useState<Budget[]>([]);
  const [recentExpenses, setRecentExpenses] = useState<Expense[]>([]);
  const navigate = useNavigate();

  useEffect(() => {
    loadDashboardData();
  }, []);

  const loadDashboardData = async () => {
    setLoading(true);
    
    try {
      const [statsData, categoryData, trendData, budgetData, expenseData] = await Promise.all([
        dashboardService.getStats().catch(() => stats),
        dashboardService.getSpendingByCategory().catch(() => []),
        dashboardService.getSpendingTrend().catch(() => []),
        dashboardService.getBudgetOverview().catch(() => []),
        dashboardService.getRecentExpenses(5).catch(() => []),
      ]);

      setStats(statsData);
      setSpendingByCategory(categoryData);
      setSpendingTrend(trendData);
      setBudgets(budgetData || []);
      setRecentExpenses(expenseData || []);
    } catch (error) {
      console.error('Error loading dashboard data:', error);
    } finally {
      setLoading(false);
    }
  };

  const getBudgetStatusClass = (budget: Budget): string => {
    if (!budget.percentage) return 'success';
    if (budget.percentage >= 100) return 'error';
    if (budget.percentage >= 80) return 'warning';
    return 'success';
  };

  const categoryChartData = {
    labels: spendingByCategory.map((c) => c.categoryName),
    datasets: [
      {
        data: spendingByCategory.map((c) => c.amount),
        backgroundColor: spendingByCategory.map((c) => c.color),
      },
    ],
  };

  const trendChartData = {
    labels: spendingTrend.map((t) => t.month),
    datasets: [
      {
        label: 'Monthly Spending',
        data: spendingTrend.map((t) => t.amount),
        borderColor: '#3f51b5',
        backgroundColor: 'rgba(63, 81, 181, 0.1)',
        tension: 0.4,
        fill: true,
      },
    ],
  };

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'bottom' as const,
      },
    },
  };

  const lineChartOptions = {
    ...chartOptions,
    plugins: {
      legend: {
        display: false,
      },
    },
    scales: {
      y: {
        beginAtZero: true,
      },
    },
  };

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', p: 8 }}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Box sx={{ maxWidth: 1400, mx: 'auto' }}>
      <Typography variant="h4" component="h1" gutterBottom>
        Dashboard
      </Typography>

      {/* Stats Cards */}
      <Grid container spacing={3} sx={{ mb: 4 }}>
        <Grid item xs={12} sm={6} md={3}>
          <Card
            sx={{
              textAlign: 'center',
              p: 2,
              transition: 'transform 0.2s',
              '&:hover': { transform: 'translateY(-4px)', boxShadow: 3 },
            }}
          >
            <WalletIcon sx={{ fontSize: 48, color: 'primary.main', mb: 1 }} />
            <Typography variant="h5" fontWeight={500}>
              {formatCurrency(stats.totalExpenses)}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Total Expenses
            </Typography>
          </Card>
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <Card
            sx={{
              textAlign: 'center',
              p: 2,
              transition: 'transform 0.2s',
              '&:hover': { transform: 'translateY(-4px)', boxShadow: 3 },
            }}
          >
            <SavingsIcon sx={{ fontSize: 48, color: 'primary.main', mb: 1 }} />
            <Typography variant="h5" fontWeight={500}>
              {formatCurrency(stats.budgetRemaining)}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Budget Remaining
            </Typography>
          </Card>
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <Card
            sx={{
              textAlign: 'center',
              p: 2,
              transition: 'transform 0.2s',
              '&:hover': { transform: 'translateY(-4px)', boxShadow: 3 },
            }}
          >
            <EventRepeatIcon sx={{ fontSize: 48, color: 'primary.main', mb: 1 }} />
            <Typography variant="h5" fontWeight={500}>
              {stats.upcomingBills}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Upcoming Bills
            </Typography>
          </Card>
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <Card
            sx={{
              textAlign: 'center',
              p: 2,
              transition: 'transform 0.2s',
              '&:hover': { transform: 'translateY(-4px)', boxShadow: 3 },
            }}
          >
            <FlagIcon sx={{ fontSize: 48, color: 'primary.main', mb: 1 }} />
            <Typography variant="h5" fontWeight={500}>
              {stats.activeSavingsGoals}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Active Goals
            </Typography>
          </Card>
        </Grid>
      </Grid>

      {/* Charts Row */}
      <Grid container spacing={3} sx={{ mb: 4 }}>
        <Grid item xs={12} md={6}>
          <Card sx={{ minHeight: 400 }}>
            <CardHeader title="Spending by Category" />
            <CardContent>
              <Box sx={{ height: 300, display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                {spendingByCategory.length > 0 ? (
                  <Doughnut data={categoryChartData} options={chartOptions} />
                ) : (
                  <Typography color="text.secondary">No spending data available</Typography>
                )}
              </Box>
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12} md={6}>
          <Card sx={{ minHeight: 400 }}>
            <CardHeader title="Spending Trend" />
            <CardContent>
              <Box sx={{ height: 300, display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
                {spendingTrend.length > 0 ? (
                  <Line data={trendChartData} options={lineChartOptions} />
                ) : (
                  <Typography color="text.secondary">No trend data available</Typography>
                )}
              </Box>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Budget Overview */}
      {budgets.length > 0 && (
        <Card sx={{ mb: 4 }}>
          <CardHeader
            title="Budget Overview"
            action={
              <Button color="primary" onClick={() => navigate('/budgets')}>
                View All
              </Button>
            }
          />
          <CardContent>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
              {budgets.slice(0, 5).map((budget) => (
                <Box key={budget.id}>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                    <Typography fontWeight={500}>{budget.category?.name}</Typography>
                    <Typography color="text.secondary" variant="body2">
                      {formatCurrency(budget.spent || 0)} / {formatCurrency(budget.amount)}
                    </Typography>
                  </Box>
                  <LinearProgress
                    variant="determinate"
                    value={Math.min(budget.percentage || 0, 100)}
                    color={getBudgetStatusClass(budget) as 'success' | 'warning' | 'error'}
                    sx={{ height: 8, borderRadius: 4 }}
                  />
                </Box>
              ))}
            </Box>
          </CardContent>
        </Card>
      )}

      {/* Recent Expenses */}
      {recentExpenses.length > 0 && (
        <Card>
          <CardHeader
            title="Recent Expenses"
            action={
              <Button color="primary" onClick={() => navigate('/expenses')}>
                View All
              </Button>
            }
          />
          <CardContent>
            <TableContainer>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Date</TableCell>
                    <TableCell>Description</TableCell>
                    <TableCell>Category</TableCell>
                    <TableCell align="right">Amount</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {recentExpenses.map((expense) => (
                    <TableRow key={expense.id}>
                      <TableCell>{formatDate(expense.date)}</TableCell>
                      <TableCell>{expense.description}</TableCell>
                      <TableCell>{expense.category?.name}</TableCell>
                      <TableCell align="right" sx={{ color: 'primary.main', fontWeight: 500 }}>
                        {formatCurrency(expense.amount)}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          </CardContent>
        </Card>
      )}
    </Box>
  );
};

export default Dashboard;

// frontend/src/app/features/dashboard/dashboard.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatTableModule } from '@angular/material/table';
import { Router } from '@angular/router';
import { NgChartsModule } from 'ng2-charts';
import { ChartConfiguration, ChartType } from 'chart.js';
import { DashboardService } from '../../core/services/dashboard.service';
import { DashboardStats, SpendingByCategory, SpendingTrend } from '../../core/models/dashboard.model';
import { Expense } from '../../core/models/expense.model';
import { Budget } from '../../core/models/budget.model';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatIconModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatTableModule,
    NgChartsModule
  ],
  template: `
    <div class="dashboard-container">
      <h1>Dashboard</h1>

      <mat-card *ngIf="loading" class="loading-card">
        <mat-spinner></mat-spinner>
      </mat-card>

      <div *ngIf="!loading">
        <!-- Stats Cards -->
        <div class="stats-grid">
          <mat-card class="stat-card">
            <mat-icon class="stat-icon">account_balance_wallet</mat-icon>
            <div class="stat-value">\${{ stats.totalExpenses | number:'1.2-2' }}</div>
            <div class="stat-label">Total Expenses</div>
          </mat-card>

          <mat-card class="stat-card">
            <mat-icon class="stat-icon">savings</mat-icon>
            <div class="stat-value">\${{ stats.budgetRemaining | number:'1.2-2' }}</div>
            <div class="stat-label">Budget Remaining</div>
          </mat-card>

          <mat-card class="stat-card">
            <mat-icon class="stat-icon">event_repeat</mat-icon>
            <div class="stat-value">{{ stats.upcomingBills }}</div>
            <div class="stat-label">Upcoming Bills</div>
          </mat-card>

          <mat-card class="stat-card">
            <mat-icon class="stat-icon">flag</mat-icon>
            <div class="stat-value">{{ stats.activeSavingsGoals }}</div>
            <div class="stat-label">Active Goals</div>
          </mat-card>
        </div>

        <!-- Charts Row -->
        <div class="charts-row">
          <mat-card class="chart-card">
            <mat-card-header>
              <mat-card-title>Spending by Category</mat-card-title>
            </mat-card-header>
            <mat-card-content>
              <div class="chart-container">
                <canvas baseChart
                  *ngIf="hasCategoryChartData"
                  [type]="categoryChartType"
                  [data]="categoryChartData"
                  [options]="categoryChartOptions">
                </canvas>
                <div *ngIf="!hasCategoryChartData" class="no-data">
                  No spending data available
                </div>
              </div>
            </mat-card-content>
          </mat-card>

          <mat-card class="chart-card">
            <mat-card-header>
              <mat-card-title>Spending Trend</mat-card-title>
            </mat-card-header>
            <mat-card-content>
              <div class="chart-container">
                <canvas baseChart
                  *ngIf="hasTrendChartData"
                  [type]="trendChartType"
                  [data]="trendChartData"
                  [options]="trendChartOptions">
                </canvas>
                <div *ngIf="!hasTrendChartData" class="no-data">
                  No trend data available
                </div>
              </div>
            </mat-card-content>
          </mat-card>
        </div>

        <!-- Budget Overview -->
        <mat-card class="section-card" *ngIf="budgets.length > 0">
          <mat-card-header>
            <mat-card-title>Budget Overview</mat-card-title>
            <button mat-button color="primary" (click)="navigateTo('/budgets')">
              View All
            </button>
          </mat-card-header>
          <mat-card-content>
            <div class="budget-list">
              <div *ngFor="let budget of budgets.slice(0, 5)" class="budget-item">
                <div class="budget-header">
                  <span class="budget-name">{{ budget.category?.name }}</span>
                  <span class="budget-amounts">
                    \${{ budget.spent | number:'1.0-0' }} / \${{ budget.amount | number:'1.0-0' }}
                  </span>
                </div>
                <mat-progress-bar 
                  mode="determinate" 
                  [value]="budget.percentage"
                  [class]="getBudgetStatusClass(budget)">
                </mat-progress-bar>
              </div>
            </div>
          </mat-card-content>
        </mat-card>

        <!-- Recent Expenses -->
        <mat-card class="section-card" *ngIf="recentExpenses.length > 0">
          <mat-card-header>
            <mat-card-title>Recent Expenses</mat-card-title>
            <button mat-button color="primary" (click)="navigateTo('/expenses')">
              View All
            </button>
          </mat-card-header>
          <mat-card-content>
            <table mat-table [dataSource]="recentExpenses" class="expenses-table">
              <ng-container matColumnDef="date">
                <th mat-header-cell *matHeaderCellDef>Date</th>
                <td mat-cell *matCellDef="let expense">{{ expense.date | date:'short' }}</td>
              </ng-container>

              <ng-container matColumnDef="description">
                <th mat-header-cell *matHeaderCellDef>Description</th>
                <td mat-cell *matCellDef="let expense">{{ expense.description }}</td>
              </ng-container>

              <ng-container matColumnDef="category">
                <th mat-header-cell *matHeaderCellDef>Category</th>
                <td mat-cell *matCellDef="let expense">
                  <mat-icon [style.color]="expense.category?.color">
                    {{ expense.category?.icon }}
                  </mat-icon>
                  {{ expense.category?.name }}
                </td>
              </ng-container>

              <ng-container matColumnDef="amount">
                <th mat-header-cell *matHeaderCellDef>Amount</th>
                <td mat-cell *matCellDef="let expense" class="amount-cell">
                  \${{ expense.amount | number:'1.2-2' }}
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
              <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
            </table>
          </mat-card-content>
        </mat-card>
      </div>
    </div>
  `,
  styles: [`
    .dashboard-container {
      max-width: 1400px;
      margin: 0 auto;
      padding: 20px;
    }

    h1 {
      margin-bottom: 20px;
    }

    .loading-card {
      display: flex;
      justify-content: center;
      padding: 60px;
    }

    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 20px;
      margin-bottom: 30px;
    }

    .stat-card {
      text-align: center;
      padding: 30px 20px;
      transition: transform 0.2s;
    }

    .stat-card:hover {
      transform: translateY(-4px);
      box-shadow: 0 4px 8px rgba(0,0,0,0.2);
    }

    .stat-icon {
      font-size: 48px;
      width: 48px;
      height: 48px;
      color: #3f51b5;
      margin-bottom: 10px;
    }

    .stat-value {
      font-size: 32px;
      font-weight: 500;
      margin: 10px 0;
    }

    .stat-label {
      color: rgba(0, 0, 0, 0.6);
      font-size: 14px;
    }

    .charts-row {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
      gap: 20px;
      margin-bottom: 30px;
    }

    .chart-card {
      min-height: 400px;
    }

    .chart-container {
      position: relative;
      height: 300px;
      padding: 10px;
    }

    .no-data {
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100%;
      color: rgba(0, 0, 0, 0.4);
    }

    .section-card {
      margin-bottom: 30px;
    }

    mat-card-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 20px;
    }

    .budget-list {
      display: flex;
      flex-direction: column;
      gap: 20px;
    }

    .budget-item {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .budget-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .budget-name {
      font-weight: 500;
    }

    .budget-amounts {
      color: rgba(0, 0, 0, 0.6);
      font-size: 14px;
    }

    .budget-good::ng-deep .mat-progress-bar-fill::after {
      background-color: #4CAF50;
    }

    .budget-warning::ng-deep .mat-progress-bar-fill::after {
      background-color: #FF9800;
    }

    .budget-exceeded::ng-deep .mat-progress-bar-fill::after {
      background-color: #F44336;
    }

    .expenses-table {
      width: 100%;
    }

    .amount-cell {
      font-weight: 500;
      color: #3f51b5;
    }

    @media (max-width: 768px) {
      .stats-grid {
        grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      }

      .charts-row {
        grid-template-columns: 1fr;
      }
    }
  `]
})
export class DashboardComponent implements OnInit {
  loading = true;
  stats: DashboardStats = {
    totalExpenses: 0,
    totalBudget: 0,
    budgetRemaining: 0,
    budgetPercentage: 0,
    upcomingBills: 0,
    activeSavingsGoals: 0,
    totalSaved: 0
  };
  budgets: Budget[] = [];
  recentExpenses: Expense[] = [];
  displayedColumns = ['date', 'description', 'category', 'amount'];

  // Category Chart
  categoryChartType: ChartType = 'doughnut';
  categoryChartData: ChartConfiguration['data'] = {
    labels: [],
    datasets: [{
      data: [],
      backgroundColor: []
    }]
  };
  categoryChartOptions: ChartConfiguration['options'] = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'bottom'
      }
    }
  };

  // Trend Chart
  trendChartType: ChartType = 'line';
  trendChartData: ChartConfiguration['data'] = {
    labels: [],
    datasets: [{
      label: 'Monthly Spending',
      data: [],
      borderColor: '#3f51b5',
      backgroundColor: 'rgba(63, 81, 181, 0.1)',
      tension: 0.4,
      fill: true
    }]
  };
  trendChartOptions: ChartConfiguration['options'] = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        display: false
      }
    },
    scales: {
      y: {
        beginAtZero: true
      }
    }
  };

  constructor(
    private dashboardService: DashboardService,
    private router: Router
  ) {}

  ngOnInit() {
    this.loadDashboardData();
  }

  loadDashboardData() {
    this.loading = true;
    let completedRequests = 0;
    const totalRequests = 5;

    const checkComplete = () => {
      completedRequests++;
      if (completedRequests === totalRequests) {
        this.loading = false;
      }
    };

    // Load stats
    this.dashboardService.getStats().subscribe({
      next: (stats) => {
        this.stats = stats;
        checkComplete();
      },
      error: (err) => {
        console.error('Error loading stats:', err);
        checkComplete();
      }
    });

    // Load spending by category
    this.dashboardService.getSpendingByCategory().subscribe({
      next: (data) => {
        if (data.length > 0) {
          this.categoryChartData = {
            labels: data.map(d => d.categoryName),
            datasets: [{
              data: data.map(d => d.amount),
              backgroundColor: data.map(d => d.color)
            }]
          };
        }
        checkComplete();
      },
      error: (err) => {
        console.error('Error loading spending by category:', err);
        checkComplete();
      }
    });

    // Load spending trend
    this.dashboardService.getSpendingTrend().subscribe({
      next: (data) => {
        if (data.length > 0) {
          this.trendChartData = {
            labels: data.map(d => d.month),
            datasets: [{
              label: 'Monthly Spending',
              data: data.map(d => d.amount),
              borderColor: '#3f51b5',
              backgroundColor: 'rgba(63, 81, 181, 0.1)',
              tension: 0.4,
              fill: true
            }]
          };
        }
        checkComplete();
      },
      error: (err) => {
        console.error('Error loading spending trend:', err);
        checkComplete();
      }
    });

    // Load budget overview
    this.dashboardService.getBudgetOverview().subscribe({
      next: (budgets) => {
        this.budgets = budgets || [];
        checkComplete();
      },
      error: (err) => {
        console.error('Error loading budget overview:', err);
        this.budgets = [];
        checkComplete();
      }
    });

    // Load recent expenses
    this.dashboardService.getRecentExpenses(5).subscribe({
      next: (expenses) => {
        this.recentExpenses = expenses || [];
        checkComplete();
      },
      error: (err) => {
        console.error('Error loading recent expenses:', err);
        this.recentExpenses = [];
        checkComplete();
      }
    });
  }

  getBudgetStatusClass(budget: Budget): string {
    if (!budget.percentage) return 'budget-good';
    if (budget.percentage >= 100) return 'budget-exceeded';
    if (budget.percentage >= 80) return 'budget-warning';
    return 'budget-good';
  }

  navigateTo(path: string) {
    this.router.navigate([path]);
  }

  get hasCategoryChartData(): boolean {
    return (this.categoryChartData.labels?.length ?? 0) > 0;
  }

  get hasTrendChartData(): boolean {
    return (this.trendChartData.labels?.length ?? 0) > 0;
  }
}
